version: "3.9"
services:

  sing-box:
    build:
      context: .
      dockerfile: sing-box.dockerfile
    network_mode: 'host'
    volumes:
      - ./config:/etc/sing-box
      - ./traefik:/etc/traefik
    command: "getcert.sh && sing-box run -c /etc/sing-box/config.json"
    restart: always

  alist:
    restart: 'always'
    volumes:
      - ./alist:/opt/alist/data
      - ./LocalStorage:/mnt/Localstorage
    network_mode: "host"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    container_name: alist
    image: xhofe/alist:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alist.rule=Host(``)"
      - "traefik.http.routers.alist.entrypoints=tlsweb"
      - "traefik.http.services.alist.loadbalancer.server.port=5244"
      - "traefik.http.routers.alist.tls=true"
      - "traefik.http.routers.alist.tls.certresolver=gts"

  adguard:
    image: adguard/adguardhome:latest
    network_mode: 'host'
    volumes:
      - ./adguard_data:/opt/adguardhome/work
      - ./adguard_config:/opt/adguardhome/conf
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(``)"
      - "traefik.http.routers.adguard.entrypoints=tlsweb"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.tls.certresolver=gts"

  traefik:
    image: traefik:latest
    environment:
      - CF_API_EMAIL=
      - CF_API_KEY=
    network_mode: 'host'
    volumes:
      - ./traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
