version: "3.7"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ${caddyfile}:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

  fileserver:
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ${files}:/srv
      - ${filebrowser.db}:/database/filebrowser.db
      - ${settings.json}:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
volumes:
  caddy-config:
  caddy-data:
