entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: tlsweb
          scheme: https
  tlsweb:
    address: :443
    http2:
      maxConcurrentStreams: 10

providers:
  file:
    filename: /etc/traefik/sslproxy.yaml
    watch: true

log:
  level: DEBUG
