name: sing-box-builder

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */8 * * *' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: clone sing-box repo
        run: git clone https://github.com/SagerNet/sing-box.git
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: sing-box
          platforms: linux/amd64,linux/arm64
          file: sing-box/Dockerfile
          tags: poormancontainer/sing-box:latest
